### ISSUE TITLE
async considerations

### ISSUE THREAD

**Issue by sjkaliski** [sjkaliski/numbers.js#12]
So the other night I was wondering if anyone had thoughts on async vs sync methods. I am doing some research on how this could benefit certain math calculations, but was curious if anyone had any thoughts

**Comment by StDako** [comment]
parallelism should only really be considered when dealing with large problems, e.g. incredibly large matrix-matrix multiplication. the problem with this is that these are CPU-intensive tasks, which Node is not built for. for small tasks, there would be too much overhead for it to be worth it.
